### ISSUE TITLE
Not able to boot macos installer

### ISSUE THREAD

**Issue by mbdev0** [BenDevelopment/MacOS-XPS-9500-2020-OpenCore#2]
I've completely followed the guide, installing the BaseSystem.chunklist as well as BaseSystem.dmg and have put them in a folder called "com.apple.recovery.boot" and pasted in your EFI with the serial numbers etc changed, however im not seeing the mac-os installer option for some reason?

**Comment by BenDevelopment** [comment]
I didn't had to do the BaseSystem's things with the folder `com.apple.recovery.boot` (what is it for?). Can you boot on your USB key?

**Comment by mbdev0** [comment]
I've fixed it! On the documentation it specified the use of "macrecovery" however I just ended up using gibOS, however now i'm running into the problem that I can't see any tools, I'm a bit stumped on that

**Comment by BenDevelopment** [comment]
What do you mean by "I can't see any tools"?

**Comment by mbdev0** [comment]
Such as open shell, modgrub etc

**Comment by BenDevelopment** [comment]
As you can read here: https://github.com/BenDevelopment/MacOS-XPS-9500-2020-OpenCore#how-to-disable-cfg-lock

> WARNING: tools are disabled on this plist. To activate tools at startup, set Misc > Boot > ShowPicker=YES and Misc > Boot > HideAuxiliary=NO.
